### ISSUE TITLE
Firefox?

### ISSUE THREAD

**Issue by spekulatius** [elrumo/stackOverflow_focus#3]
Hey @elrumo 

I was wondering if there is a Firefox version or you planning on publishing one?

Cheers,
Peter

**Comment by elrumo** [comment]
Not yet, but seeing I've already had some people ask for it I'll definitely make one. Thanks for the feedback!

**Comment by spekulatius** [comment]
Okay, it should work almost out of the box - I would smoke test it, upload it to [Mozilla](https://addons.mozilla.org/en-US/firefox/) and see.

**Comment by elrumo** [comment]
Just submitted it, that was surprisingly quick. I hadn't done it earlier because I thought it would take longer. I'll update this issue once it's been approved.

**Comment by spekulatius** [comment]
Hey @elrumo 

yeah, Firefox and Chrome are very similar when it comes to extensions. Most work out of the box 👍️

Thanks for the update!

Cheers!

**Comment by sidzi** [comment]
I would also be available help if required in this.

Thanks for making this.

**Comment by elrumo** [comment]
Firefox has denied the plugin because I submitted minified code without supplying them with the non-minified code. The issue is that the code is from the [UI library I used](https://opensource.adobe.com/coral-spectrum/dist/examples/#button), another issue is that the icons from the Adobe library don't load because of security reasons. I think the best option would be to use WebPack to only import the components needed, [as seen here](https://opensource.adobe.com/coral-spectrum/dist/documentation/manual/manual.html#using-a-bundler-like-webpack), but I don't have much experience with WebPack, so help there would be appreciated.

**Comment by spekulatius** [comment]
I'm not experienced enough with webpack - just using pre-configured versions really. I've simply uploaded source code without dependencies - but that was for cases where all dependencies came via NPM.

**Comment by himittal09** [comment]
Firefox also has a pollyfill to help making the extensions made for chrome also work for firefox.
[Here is the pollyfill](https://github.com/mozilla/webextension-polyfill)

**Comment by elrumo** [comment]
@himittal09 Yesterday I re-submitted the plugin for review and should hopefully be approved soon

**Comment by elrumo** [comment]
Took some time, but it's finally available on Firefox :)

https://addons.mozilla.org/en-GB/firefox/addon/stackoverflow-focus/

**Comment by spekulatius** [comment]
Thanks @elrumo

**Comment by mutageneral** [comment]
the link now goes to a 404
