### ISSUE TITLE
Why does the new update require access to the browsing history?

### ISSUE THREAD

**Issue by eigenpaul** [elrumo/stackOverflow_focus#6]
uninstall worthy
![Screenshot from 2020-09-17 17-31-08](https://user-images.githubusercontent.com/33395806/93492959-b1bafe80-f90b-11ea-80d0-31d8c969831c.png)

**Comment by elrumo** [comment]
The browsing history? I added some extra customisation settings so the only new permissions that were added was access to tabs, to update any setting changes you make to all your open Stackoverflow tabs, and storage to locally store your settings

This is a screenshot from the Chrome developer dashboard where it asks me what permission the plugin needs and why and another screenshot of the manifest file with all the permissions I request. If anyone knows why it's requesting access to the browsing history, please let me know. 
![image](https://user-images.githubusercontent.com/36299870/93492443-b7f8ad00-f902-11ea-8d61-e2c4861ab76f.png)
 
![image](https://user-images.githubusercontent.com/36299870/93492685-fd1cdf00-f902-11ea-88bd-436e70df1616.png)

**Comment by elrumo** [comment]
And these are the new options that have been added:

![image](https://user-images.githubusercontent.com/36299870/93492833-2b022380-f903-11ea-9118-417d746ef998.png)
![image](https://user-images.githubusercontent.com/36299870/93492840-2d647d80-f903-11ea-96cd-89f699fe9020.png)

**Comment by eigenpaul** [comment]
have you tried installing it on brave? maybe it's an issue with the brave browser and its security settings

**Comment by elrumo** [comment]
I use Opera, and I just tried installing and it also asks for the browsing history, I honestly have no clue where that is coming from. I'll do some research to see if I find something, but thanks for bringing it up

**Comment by eigenpaul** [comment]
Okay, thanks for the quick response.I really hope you can resolve this, nonetheless great extension

**Comment by vantezzen** [comment]
The message comes because you requested the `"tabs"` permission in your `manifest.json`. You should be able to change this permission to `"activeTab"` which should get rid of this warning without affecting the extension.

With "tabs" permission:
<img width="187" alt="Screenshot 2020-10-01 at 11 37 34" src="https://user-images.githubusercontent.com/10333196/94793264-812e9680-03da-11eb-8b2c-5fd81282cc78.png">

With "activeTab" permission:
<img width="119" alt="Screenshot 2020-10-01 at 11 38 00" src="https://user-images.githubusercontent.com/10333196/94793305-90addf80-03da-11eb-9ad5-4e9315d405b9.png">

**Comment by elrumo** [comment]
Thank you! I'll change that. I looked everywhere but never through that the persmission to tabs could caue this, I wonder why Google made it that way.
